import { KC } from './KeyCodes'

export default [
    KC.SIN, KC.COS, KC.ARC, KC.ASIN, KC.CLX, KC.DOT, KC.D0, KC.D1,
    KC.D2, KC.D3, KC.D4, KC.D5, KC.D6, KC.D7, KC.D8, KC.D9, KC.DIV, KC.EEX, KC.LN,
    KC.LOG, KC.MUL, KC.PI, KC.POW, KC.RCL, KC.RECIPROCAL, KC.ROLL_DOWN, KC.SQRT, KC.STO,
    KC.ACOS, KC.ADD, KC.ATAN, KC.CHS, KC.CLR, KC.ENTER, KC.EXP, KC.SUB, KC.SWAP
]